name             'mysql_mapr'
maintainer       'daniel washko'
maintainer_email 'dwashko@gannett.com'
license          'All rights reserved'
description      'Installs/Configures mysql_config'
long_description 'Installs/Configures mysql_config'
version          '0.1.0'

depends 'mysql'
depends 'lvm'
depends 'selinux'
depends 'sysctl'
